openapi: 3.1.0
info:
  title: Spotigen API
  version: "1.0"

servers:
  - url: https://spotigen-chat-gpt-plugin-production.up.railway.app

paths:
  /top_tracks:
    get:
      summary: Get user's five most‑played tracks
      operationId: getTopTracks
      responses:
        "200":
          description: Top tracks returned
          content:
            application/json: {}
        "401":
          description: Authentication required

  /create_playlist:
    post:
      summary: Create a playlist
      operationId: createPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Playlist name
              required: [name]
      responses:
        "200":
          description: Playlist created
          content:
            application/json: {}
        "401":
          description: Authentication required
