openapi: 3.1.0
info:
  title: Spotigen API
  version: "1.0"

servers:
  - url: https://spotigen-chat-gpt-plugin-production.up.railway.app

paths:
  /top_tracks:
    get:
      summary: Get the user's 5 most‑played tracks
      operationId: getTopTracks
      responses:
        "200":
          description: A JSON array with the top tracks
          content:
            application/json:
              schema:
                type: array
                items: {}
        "401":
          description: Authentication required

  /create_playlist:
    post:
      summary: Create a new playlist
      operationId: createPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the playlist to create
              required: [name]
      responses:
        "200":
          description: Playlist successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  url:
                    type: string
        "401":
          description: Authentication required
