openapi: 3.1.0
info:
  title: Spotigen API
  version: "1.0"
servers:
  - url: https://spotigen-chat-gpt-plugin-production.up.railway.app
paths:
  /top_tracks:
    get:
      summary: Top Tracks
      operationId: top_tracks
      responses:
        "200":
          description: Successful Response
