name: Keep Railway Awake
on:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -fsS https://spotigen-chat-gpt-plugin-production.up.railway.app/ || true
